# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PayItForward' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayItForward
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  
  pod 'FacebookLogin'
  
  pod 'DKImagePickerController'
  pod 'DKCamera'
  
  pod 'SwiftSpinner'
  
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
end
